// Private schema: customer data and sessions are never exposed by the Data API.
export const postgresSchema = `
CREATE SCHEMA IF NOT EXISTS ocular;
CREATE TABLE IF NOT EXISTS ocular.products (id TEXT PRIMARY KEY, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ocular.orders (id TEXT PRIMARY KEY, token TEXT NOT NULL, idem TEXT UNIQUE NOT NULL, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ocular.events (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, type TEXT NOT NULL, body TEXT NOT NULL, created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ocular.sessions (token TEXT PRIMARY KEY, expires BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS ocular.rate_limits (key TEXT PRIMARY KEY, hits INTEGER NOT NULL, expires BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS ocular.notifications (id TEXT PRIMARY KEY, body TEXT NOT NULL, sent INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS ocular.settings (key TEXT PRIMARY KEY, body TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS ocular_events_created ON ocular.events(created);
CREATE INDEX IF NOT EXISTS ocular_sessions_expires ON ocular.sessions(expires);
CREATE INDEX IF NOT EXISTS ocular_rate_limits_expires ON ocular.rate_limits(expires);
ALTER TABLE ocular.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE ocular.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE ocular.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE ocular.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE ocular.rate_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE ocular.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE ocular.settings ENABLE ROW LEVEL SECURITY;
DO $roles$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN
    REVOKE ALL ON SCHEMA ocular FROM anon;
    REVOKE ALL ON ALL TABLES IN SCHEMA ocular FROM anon;
    REVOKE ALL ON ALL SEQUENCES IN SCHEMA ocular FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN
    REVOKE ALL ON SCHEMA ocular FROM authenticated;
    REVOKE ALL ON ALL TABLES IN SCHEMA ocular FROM authenticated;
    REVOKE ALL ON ALL SEQUENCES IN SCHEMA ocular FROM authenticated;
  END IF;
END $roles$;
REVOKE ALL ON SCHEMA ocular FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA ocular FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA ocular FROM PUBLIC;
`;
