/* Páginas estáticas independentes. A home e seus recursos não são gerados aqui. */
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const imageManifest = JSON.parse(fs.readFileSync(path.join(root,'assets/ensaio/manifest.json'),'utf8'));
const base = 'https://www.opticaocular.com.br';
const wa = message => `https://wa.me/5541997502091?text=${encodeURIComponent(message)}`;
const generic = wa('Olá! Vim pelo site da Óptica Ocular e gostaria de conversar com a equipe.');
const route = 'https://www.google.com/maps/dir/?api=1&destination=Rua+Bispo+Dom+Jos%C3%A9+2655+Curitiba+PR';
const arrow = '<svg class="arrow" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.3" aria-hidden="true"><path d="M5 19 19 5M5 5h14v14"/></svg>';
const chat = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M20.5 11.5a8.5 8.5 0 0 1-12.4 7.6L3 21l1.9-5.1a8.5 8.5 0 1 1 15.6-4.4Z"/><path d="M8.2 7.8c.5 3.8 2.2 5.5 5.9 6.2l1.2-1.5-2-1-1 1a6.7 6.7 0 0 1-2.8-2.8l.9-1-1-1.9Z"/></svg>';
const link = (href, text, cls = 'text-link') => `<a class="${cls}" href="${href}"${href.startsWith('https:') ? ' target="_blank" rel="noopener noreferrer"' : ''}>${text}${arrow}</a>`;
function photo(key, alt, { eager = false, cls = '', sizes = '(max-width: 760px) 100vw, 55vw', portrait = false } = {}) {
  const meta=imageManifest[key];
  const srcset=meta.widths.map(width=>`assets/ensaio/${key}-${width}.webp ${width}w`).join(', ');
  return `<img class="${cls}" src="assets/ensaio/${key}-${meta.widths.at(-1)}.webp" srcset="${srcset}" sizes="${sizes}" width="${meta.width}" height="${meta.height}" alt="${alt}" ${eager ? 'fetchpriority="high"' : 'loading="lazy"'} decoding="async">`;
}
const brand = `<span class="brand-symbol"><img src="assets/logo-dark.png" width="266" height="227" alt=""></span><img class="brand-name" src="assets/brand-text-header.svg" width="862" height="159" alt="Óptica Ocular — Tradição em cuidar dos seus olhos">`;
function header(active) {
  const nav = [['oculos','Óculos'],['lentes','Lentes'],['sobre','Nossa história'],['visite','Visite a loja']];
  return `<a class="skip" href="#conteudo">Pular para o conteúdo</a><header class="site-header"><a class="brand" href="index.html" aria-label="Óptica Ocular, início">${brand}</a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="site-nav" hidden><span>Menu</span><span class="menu-lines" aria-hidden="true"></span></button><nav id="site-nav" class="site-nav" aria-label="Navegação principal">${nav.map(([slug,label])=>`<a href="${slug}.html"${active===slug?' aria-current="page"':''}>${label}</a>`).join('')}<a class="nav-contact" href="${generic}" target="_blank" rel="noopener noreferrer">Fale conosco ${arrow}</a></nav></header>`;
}
function footer() {
  return `<footer class="site-footer"><div class="footer-top"><a class="brand" href="index.html" aria-label="Óptica Ocular, início">${brand}</a><p>Um olhar atento a você.<br>Desde 1990, em Curitiba.</p><div class="footer-social">${link('https://www.instagram.com/opticaocularctba/', 'Instagram')}${link('https://www.facebook.com/opticaocularctba/', 'Facebook')}</div></div><div class="footer-grid"><div><p class="eyebrow">Explore</p><a href="oculos-de-grau.html">Óculos de grau</a><a href="oculos-de-sol.html">Óculos de sol</a><a href="lentes.html">Lentes</a></div><div><p class="eyebrow">A Ocular</p><a href="sobre.html">Nossa história</a><a href="visite.html">Visite a loja</a><a href="duvidas.html">Dúvidas frequentes</a></div><div><p class="eyebrow">Encontre a gente</p><a href="${route}" target="_blank" rel="noopener noreferrer">Rua Bispo Dom José, 2655<br>Seminário · Curitiba, PR</a><a href="${generic}" target="_blank" rel="noopener noreferrer">(41) 99750-2091</a></div><div><p class="eyebrow">Portas abertas</p><p>Seg–sex · 9h às 18h30<br>Sábado · 9h às 13h</p><p class="small-note">Em feriados, consulte a equipe.</p></div></div><div class="footer-wordmark" aria-hidden="true"><img src="assets/ocular-wordmark.svg" width="2423" height="738" alt=""></div><div class="footer-bottom"><span>© <span data-year>2026</span> Óptica Ocular</span><span>Fotografias editoriais ilustrativas.</span><a href="privacidade.html">Privacidade</a></div></footer><a class="floating-contact" href="${generic}" target="_blank" rel="noopener noreferrer" aria-label="Conversar com a Óptica Ocular no WhatsApp">${chat}</a>`;
}
function breadcrumb(items) {
  return `<nav class="breadcrumb" aria-label="Você está aqui"><a href="index.html">Início</a>${items.map(([name,href])=>`<span aria-hidden="true">/</span>${href?`<a href="${href}">${name}</a>`:`<span aria-current="page">${name}</span>`}`).join('')}</nav>`;
}
function cta(title = 'Seu próximo olhar<br><em>começa com uma conversa.</em>', msg) {
  return `<section class="contact-strip"><div><p class="eyebrow">Vamos encontrar o seu</p><h2>${title}</h2></div><div><p>Conte o que você procura.<br>A gente cuida dos próximos passos.</p>${link(msg ? wa(msg) : generic, 'Converse com a equipe', 'button button-light')}${link('visite.html','Ou venha à loja','text-link light')}</div></section>`;
}
function steps(title = 'Uma escolha que<br><em>faz sentido para você.</em>') {
  return `<section class="section steps"><div class="section-head"><div><p class="eyebrow">O jeito Ocular de escolher</p><h2>${title}</h2></div><p>Estética e conforto se encontram<br>quando há atenção aos detalhes.</p></div><div class="step-grid"><article><span class="index">01 / CONVERSAR</span><h3>Primeiro, você.</h3><p>Sua rotina, suas preferências e o que espera dos próximos óculos.</p></article><article><span class="index">02 / EXPERIMENTAR</span><h3>Sentir a diferença.</h3><p>Proporções, encaixe e presença no rosto. A escolha também acontece no espelho.</p></article><article><span class="index">03 / ESCOLHER</span><h3>Cuidar dos detalhes.</h3><p>Armação e lentes consideradas juntas, com orientação da nossa equipe.</p></article></div></section>`;
}
const faqs = [
  ['Escolha','Preciso agendar para visitar a loja?','Você pode vir durante o horário de atendimento. Se preferir combinar sua visita ou esclarecer algo antes, converse com nossa equipe pelo WhatsApp.'],
  ['Escolha','O que levar para escolher óculos de grau?','Traga sua receita oftalmológica e, se tiver, os óculos que usa hoje. Conte como é sua rotina e o que gostaria de mudar na sua próxima escolha.'],
  ['Escolha','Posso consultar modelos pelo WhatsApp?','Sim. Diga se procura grau ou sol e descreva seu estilo. A equipe poderá informar os modelos, os valores e a disponibilidade atual em loja.'],
  ['Lentes','Qual é a diferença entre monofocais e multifocais?','Monofocais têm uma correção para uma distância de visão. Multifocais progressivas reúnem campos para perto, intermediário e longe. A escolha considera sua receita e suas atividades.'],
  ['Lentes','Vocês trabalham com lentes fotocromáticas?','Sim. Consulte as opções e a compatibilidade com sua receita. Essas lentes mudam de tonalidade conforme as condições de luz; o comportamento depende da tecnologia e do ambiente.'],
  ['Lentes','Posso trocar as lentes e manter minha armação?','A equipe precisa avaliar o estado e a compatibilidade da armação com as novas lentes. Traga seus óculos à loja para conversarmos sobre as possibilidades.'],
  ['Compra','Como consultar preços e formas de pagamento?','Converse com a equipe ou visite a loja. O orçamento depende da armação, da receita, da tecnologia das lentes e dos tratamentos escolhidos. As condições são informadas no atendimento.'],
  ['Compra','Qual é o prazo para meus óculos ficarem prontos?','O prazo varia conforme as lentes e a disponibilidade. Nossa equipe informa a previsão para o seu pedido no momento do orçamento.'],
  ['Visita','Onde fica a Óptica Ocular?','Na Rua Bispo Dom José, 2655, Seminário, Curitiba, PR. O CEP é 80440-080. Na página Visite a loja você encontra o mapa e o link para traçar sua rota.'],
  ['Visita','Quais são os horários de atendimento?','Segunda a sexta, das 9h às 18h30. Aos sábados, das 9h às 13h. Domingo fechado. Em feriados, consulte a equipe antes da visita.']
];
function faqRows(items = faqs, searchable = false) {
  return items.map(([group,q,a],index)=>`<details class="question"${searchable?` data-faq data-category="${group}"`:''}><summary><span>${q}</span><span class="plus" aria-hidden="true"></span></summary><div class="answer"><p>${a}</p>${q.startsWith('Onde')?link('visite.html','Ver localização'):''}</div></details>`).join('');
}
function preference(type) {
  const solar=type==='sol';
  const values=solar?['Discreto','Marcante','Ainda vou descobrir']:['Leveza','Presença','Ainda vou descobrir'];
  return `<section class="section preference-section"><div><p class="eyebrow">Seu estilo, seu ponto de partida</p><h2>Como você quer<br><em>se reconhecer?</em></h2><p>Uma preferência já é um bom começo.<br>O resto a gente descobre na conversa.</p></div><form class="preference-form" data-category="Óculos de ${type}"><fieldset><legend>O que combina mais com você?</legend>${values.map((v,i)=>`<label class="preference-option"><input type="radio" name="estilo" value="${v}" ${i===0?'checked':''}><span><span class="choice-index">0${i+1}</span>${v}</span><span class="radio-mark" aria-hidden="true"></span></label>`).join('')}</fieldset><p class="preference-copy" aria-live="polite">${solar?'Linhas discretas para acompanhar diferentes momentos.':'Uma presença sutil, com atenção ao encaixe e ao conforto.'}</p>${link(wa(`Olá! Tenho interesse em óculos de ${type} e gostaria de conhecer as opções disponíveis.`),'Levar minha preferência à equipe','button preference-link')}<noscript><p class="small-note">Conte sua preferência à equipe no WhatsApp.</p></noscript></form></section>`;
}
const pages = [];
function page(slug,title,description,active,body,{og='olhares-geracoes',cls=''}={}) {
  const filename=slug+'.html';
  const html=`<!doctype html>
<html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title} | Óptica Ocular</title><meta name="description" content="${description}"><meta name="theme-color" content="#231f20"><link rel="canonical" href="${base}/${filename}"><meta property="og:type" content="website"><meta property="og:locale" content="pt_BR"><meta property="og:site_name" content="Óptica Ocular"><meta property="og:title" content="${title} | Óptica Ocular"><meta property="og:description" content="${description}"><meta property="og:url" content="${base}/${filename}"><meta property="og:image" content="${base}/assets/ensaio/${og}-social.jpg"><meta property="og:image:alt" content="Ensaio editorial em preto e branco da Óptica Ocular"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="assets/logo-dark.png"><link rel="preload" href="assets/fonts/cormorant-garamond-normal-latin.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="assets/fonts/manrope-normal-latin.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="fonts.css"><link rel="stylesheet" href="interiores.css"><script src="interiores.js" defer></script></head><body class="interior ${cls}">${header(active)}<main id="conteudo">${body}</main>${footer()}</body></html>`;
  fs.writeFileSync(path.join(root,filename),slug==='404'?html.replace('<head>','<head><meta name="robots" content="noindex">'):html,'utf8');
  if(slug!=='404')pages.push(filename);
}

page('oculos','Óculos de grau e de sol em Curitiba','Explore óculos de grau e de sol. Encontre seu estilo com a orientação da Óptica Ocular, em Curitiba desde 1990.','oculos',`
${breadcrumb([['Óculos']])}<section class="collection-hero"><div class="collection-hero-copy"><p class="eyebrow">Grau & sol · Ocular</p><h1>Um olhar.<br>Infinitas<br><em>possibilidades.</em></h1><p class="lead">Para ver o mundo.<br>Para se reconhecer nele.</p><p class="muted">Óculos que encontram o seu jeito de ser.<br>Uma escolha feita de perto, com você.</p>${link('#colecoes','Encontre seu próximo óculos','button')}<span class="hero-footnote">CURITIBA, DESDE 1990 <span aria-hidden="true">—</span> ESCOLHAS COM PERSONALIDADE</span></div><div class="portrait-composition"><figure class="portrait-main">${photo('grau-retrato','Modelo com armação de grau preta e camisa branca, em ensaio editorial.',{eager:true,portrait:true})}<figcaption>01 / OLHARES OCULAR</figcaption></figure><figure class="portrait-inset">${photo('sol-retrato','Modelo com óculos de sol pretos sob a luz natural.',{eager:true,portrait:true,sizes:'(max-width: 760px) 32vw, 20vw'})}</figure></div></section>
<div class="editorial-line"><span>Estética. Conforto. Personalidade.</span><span>O seu olhar é único.</span></div>
<section class="section" id="colecoes"><div class="section-head"><div><p class="eyebrow">Duas maneiras de olhar</p><h2>Seu estilo.<br><em>Em todos os momentos.</em></h2></div><p>Comece pelo que você procura.<br>Encontre o que combina com você.</p></div><div class="collection-grid"><a class="collection-card" href="oculos-de-grau.html"><div class="card-photo"><img src="assets/grau-editorial-v2.jpg" width="1536" height="1024" loading="lazy" alt="Armação de grau preta sobre uma superfície de pedra clara."><span class="card-number">01</span><span class="round-arrow">${arrow}</span></div><div class="card-heading"><h3>Óculos de <em>grau.</em></h3><span>Para a sua rotina</span></div><p>Uma presença que diz muito sobre você.</p></a><a class="collection-card" href="oculos-de-sol.html"><div class="card-photo"><img src="assets/solar-editorial-v2.jpg" width="1536" height="1024" loading="lazy" alt="Óculos de sol pretos em uma composição editorial com luz e sombra."><span class="card-number">02</span><span class="round-arrow">${arrow}</span></div><div class="card-heading"><h3>Óculos de <em>sol.</em></h3><span>Para os seus dias de luz</span></div><p>Personalidade para acompanhar novos caminhos.</p></a></div><p class="small-note collection-note">Imagens ilustrativas. Consulte modelos e disponibilidade com nossa equipe.</p></section>
<section class="editorial-feature"><figure>${photo('olhares-geracoes','Duas modelos de gerações diferentes usando óculos de grau, em fotografia editorial.',{sizes:'(max-width: 760px) 100vw, 58vw'})}<figcaption>OLHARES OCULAR / UM ENSAIO SOBRE SE RECONHECER</figcaption></figure><div><p class="eyebrow">Além da primeira impressão</p><h2>Não existe um<br>olhar <em>igual ao seu.</em></h2><p>Há quem prefira a leveza. Há quem goste de marcar presença. E há quem queira experimentar algo novo.</p><p>Na Ocular, a escolha começa por entender você. Depois, vem o prazer de encontrar o par que faz sentido.</p>${link('sobre.html','Conheça o nosso jeito')}</div></section>${steps()}${cta()}`);

page('oculos-de-grau','Óculos de grau em Curitiba','Armações de grau, conforto e personalidade. Conheça o atendimento da Óptica Ocular e encontre seus próximos óculos em Curitiba.','oculos',`
${breadcrumb([['Óculos','oculos.html'],['Óculos de grau']])}<section class="split-hero"><div class="split-copy"><p class="eyebrow">01 / Óculos de grau</p><h1>Parte do<br>seu dia.<br><em>Parte de você.</em></h1><p class="lead">Os melhores encontros<br>parecem naturais.</p><p class="muted">Sua armação acompanha seu rosto, sua rotina e a forma como você se expressa.</p>${link('#sua-escolha','Descubra sua próxima armação','button')}</div><figure class="split-portrait">${photo('grau-retrato','Modelo de camisa branca com armação de grau preta. Fotografia editorial ilustrativa.',{eager:true,portrait:true})}<figcaption>OLHARES OCULAR / GRAU</figcaption></figure></section>
<section class="section statement" id="sua-escolha"><p class="eyebrow">A beleza está no encontro</p><h2>É sobre o que você vê.<br><em>E como você se sente.</em></h2><p>O desenho chama a atenção. O conforto faz querer ficar.<br>Na loja, você experimenta, compara e escolhe com orientação.</p></section>
<section class="product-story"><figure><img src="assets/grau-editorial-v2.jpg" width="1536" height="1024" alt="Detalhe ilustrativo de uma armação preta de grau sobre pedra clara." loading="lazy"><figcaption>FORMA, MATÉRIA & PERSONALIDADE</figcaption></figure><div class="detail-list"><article><span class="index">01</span><div><h3>Proporção.</h3><p>Um desenho que conversa com seu rosto e com a presença que você procura.</p></div></article><article><span class="index">02</span><div><h3>Encaixe.</h3><p>Apoio no nariz, posição das hastes e conforto para acompanhar seu dia.</p></div></article><article><span class="index">03</span><div><h3>Conjunto.</h3><p>Armação e lentes escolhidas em harmonia, considerando sua receita.</p></div></article></div></section>
${preference('grau')}<section class="next-chapter"><span class="eyebrow">Complete sua escolha</span><h2>Agora, vamos olhar<br><em>para as lentes.</em></h2>${link('lentes.html','Conheça as possibilidades','button')}</section>${cta('Vamos encontrar<br><em>seu próximo par.</em>','Olá! Quero conhecer as armações de grau disponíveis na Óptica Ocular.')}`,{og:'grau-retrato'});

page('oculos-de-sol','Óculos de sol em Curitiba','Óculos de sol com personalidade e orientação para escolher. Conheça a Óptica Ocular, na Rua Bispo Dom José, 2655, em Curitiba.','oculos',`
${breadcrumb([['Óculos','oculos.html'],['Óculos de sol']])}<section class="split-hero solar-hero"><div class="split-copy"><p class="eyebrow">02 / Óculos de sol</p><h1>Encontre<br>a sua<br><em>melhor luz.</em></h1><p class="lead">Uma nova perspectiva.<br>O mesmo você.</p><p class="muted">Linhas que revelam personalidade. Uma escolha que acompanha a cidade, a viagem e o tempo ao ar livre.</p>${link('#descubra','Explore seu próximo solar','button button-light')}</div><figure class="split-portrait">${photo('sol-retrato','Modelo com óculos de sol pretos e camisa escura, em um ensaio com luz natural.',{eager:true,portrait:true})}<figcaption>OLHARES OCULAR / SOL</figcaption></figure></section>
<section class="section statement" id="descubra"><p class="eyebrow">Presença sem esforço</p><h2>O dia muda.<br><em>Seu estilo acompanha.</em></h2><p>Do traço discreto ao desenho marcante.<br>Experimente proporções e descubra a sua.</p></section>
<section class="product-story"><figure><img src="assets/solar-editorial-v2.jpg" width="1536" height="1024" alt="Óculos de sol pretos sobre pedra clara, em fotografia ilustrativa." loading="lazy"><figcaption>LUZ, SOMBRA & EXPRESSÃO</figcaption></figure><div class="detail-list"><article><span class="index">01</span><div><h3>Seu desenho.</h3><p>Linhas suaves ou formas definidas. A expressão que combina com seu momento.</p></div></article><article><span class="index">02</span><div><h3>Seu conforto.</h3><p>Experimente o apoio e a estabilidade da armação. Um bom encaixe faz parte da escolha.</p></div></article><article><span class="index">03</span><div><h3>Sua orientação.</h3><p>Converse sobre as características das lentes e as opções para o uso que você tem em mente.</p></div></article></div></section>
${preference('sol')}<section class="cross-category"><p class="eyebrow">Um par para cada momento</p><h2>E para o seu <em>dia a dia?</em></h2>${link('oculos-de-grau.html','Explore os óculos de grau')}</section>${cta('A próxima escolha<br><em>pode ser a sua favorita.</em>','Olá! Quero conhecer os óculos de sol disponíveis na Óptica Ocular.')}`,{og:'sol-retrato'});

const lensInfo = [
 ['monofocais','01','Monofocais','Um foco.<br><em>Muitos momentos.</em>','Uma correção para uma distância de visão, conforme sua receita. Uma possibilidade para atividades de perto ou para enxergar de longe.','Traga sua receita e conte como usa seus óculos. A equipe orienta sobre materiais, espessuras e tratamentos disponíveis.'],
 ['multifocais','02','Multifocais','Diferentes distâncias.<br><em>Um mesmo olhar.</em>','Lentes progressivas reúnem campos de visão para perto, intermediário e longe, com transição entre eles.','Armação, medidas e rotina entram na conversa. Conheça as opções com a equipe e esclareça suas dúvidas sobre a adaptação.'],
 ['fotocromaticas','03','Fotocromáticas','A luz muda.<br><em>As lentes também.</em>','Lentes que mudam de tonalidade conforme as condições de luz. A resposta varia com a tecnologia, a temperatura e o ambiente.','Converse sobre seu uso em espaços internos e externos. A equipe explica as opções e a compatibilidade com sua receita.']
];
page('lentes','Lentes para sua rotina','Conheça lentes monofocais, multifocais e fotocromáticas. Orientação para sua receita e rotina na Óptica Ocular em Curitiba.','lentes',`
${breadcrumb([['Lentes']])}<section class="lens-hero"><div><p class="eyebrow">O essencial, em cada detalhe</p><h1>A vida merece<br><em>um olhar atento.</em></h1><div class="lens-hero-bottom"><p class="lead">Sua receita é o começo.<br>Sua rotina completa a escolha.</p>${link('#possibilidades','Conheça as lentes')}</div></div><figure>${photo('lentes-detalhe','Detalhe de lentes transparentes em uma armação preta sobre pedra clara.',{eager:true,sizes:'100vw'})}<figcaption>OLHARES OCULAR / A PRECISÃO DO ESSENCIAL</figcaption></figure></section>
<section class="section lens-discovery" id="possibilidades"><div class="section-head"><div><p class="eyebrow">Entenda as possibilidades</p><h2>Uma lente para<br><em>o seu jeito de viver.</em></h2></div><p>A escolha considera sua receita,<br>a armação e suas atividades.</p></div><div class="lens-tablist" role="tablist" aria-label="Explore os tipos de lentes" hidden>${lensInfo.map(([id,n,title],i)=>`<button type="button" id="tab-${id}" role="tab" aria-selected="${i===0}" aria-controls="${id}" tabindex="${i===0?0:-1}"><span>${n}</span>${title}<span class="tab-arrow" aria-hidden="true">↗</span></button>`).join('')}</div>${lensInfo.map(([id,n,title,h,p,note],i)=>`<article class="lens-panel" id="${id}"><div><p class="eyebrow">${n} / ${title}</p><h3>${h}</h3></div><div><p class="panel-lead">${p}</p><p class="muted">${note}</p>${link(wa(`Olá! Gostaria de orientação sobre lentes ${title.toLowerCase()}.`),'Conversar sobre estas lentes')}</div></article>`).join('')}</section>
<section class="brand-section"><p class="eyebrow">Tecnologia e possibilidades de escolha</p><div class="brand-grid">${[['hoya-clean','HOYA'],['zeiss-clean','ZEISS'],['varilux-clean','Varilux'],['rodenstock','Rodenstock'],['crizal-clean','Crizal'],['transitions-clean','Transitions']].map(([src,alt])=>`<img src="assets/brands/${src}.png" alt="${alt}" width="160" height="70" loading="lazy">`).join('')}</div><p class="small-note">Consulte linhas, tratamentos e disponibilidade com nossa equipe.</p></section>
<section class="editorial-feature lens-care"><figure>${photo('gesto-cuidado','Mãos segurando uma armação com lentes transparentes. Cena editorial ilustrativa.')}<figcaption>ATENÇÃO AO QUE FAZ DIFERENÇA</figcaption></figure><div><p class="eyebrow">A escolha acontece nos detalhes</p><h2>Mais do que<br>tecnologia.<br><em>Orientação.</em></h2><p>Você lê, trabalha, dirige, descansa. Conte quais momentos ocupam seu dia e o que espera dos próximos óculos.</p><p>A partir da sua receita, nossa equipe ajuda a entender as opções, sem apressar sua escolha.</p>${link('visite.html','Traga sua receita. Vamos conversar.')}</div></section><section class="section compact-faq"><div><p class="eyebrow">Vale saber</p><h2>Suas dúvidas,<br><em>com clareza.</em></h2>${link('duvidas.html','Todas as dúvidas')}</div><div>${faqRows(faqs.filter(f=>f[0]==='Lentes').slice(0,3))}</div></section>${cta()}`,{og:'lentes-detalhe'});

page('sobre','Nossa história, desde 1990','Conheça a história da Óptica Ocular. Desde 1990, experiência óptica e atenção a cada escolha em Curitiba.','sobre',`
${breadcrumb([['Nossa história']])}<section class="about-hero"><div class="about-heading"><p class="eyebrow">A Ocular · Curitiba</p><h1>O tempo passa.<br>O cuidado<br><em>permanece.</em></h1><p class="lead">Uma história feita de pessoas.<br>E de muitos novos olhares.</p></div><div class="since"><span class="eyebrow">O nosso primeiro capítulo</span><span class="since-year">1990<span aria-hidden="true">.</span></span><p>Mais do que escolher óculos.<br>Construir relações.</p></div></section><figure class="about-panorama">${photo('olhares-geracoes','Duas modelos com óculos de grau, representando diferentes gerações em ensaio ilustrativo.',{eager:true,sizes:'100vw'})}<figcaption>OLHARES OCULAR / ENSAIO EDITORIAL ILUSTRATIVO</figcaption></figure>
<section class="section history-text"><div><p class="eyebrow">Nossa origem</p><h2>A experiência<br>de quem sempre<br><em>olhou de perto.</em></h2></div><div><p class="large-copy">Em 1990, Laércio deu início à Óptica Ocular, no bairro Portão, em Curitiba.</p><p>Sua experiência como técnico de laboratório estava na origem de um cuidado que ia além da armação: entender o que fazia diferença para cada pessoa.</p><p>Com o tempo, a história ganhou um novo endereço na Rua Bispo Dom José. A atenção à escolha e o vínculo com os clientes continuam fazendo parte do nosso jeito de trabalhar.</p><div class="signature-rule"><span>Óptica Ocular</span><span>Desde 1990.</span></div></div></section>
<section class="editorial-feature about-care"><figure>${photo('gesto-cuidado','Detalhe editorial de mãos segurando óculos, como expressão de cuidado.')}<figcaption>O CUIDADO SE REVELA NOS DETALHES</figcaption></figure><div><p class="eyebrow">Nosso jeito</p><h2>Ouvir primeiro.<br><em>Escolher juntos.</em></h2><p>Uma boa escolha começa com uma conversa. Sobre a sua rotina. Sobre o que incomoda. Sobre como você quer se sentir.</p><p>É assim que experiência e atenção se encontram, a cada visita.</p>${link('visite.html','Venha conhecer a Ocular')}</div></section><section class="section values-editorial"><p class="eyebrow">O que nos acompanha</p><div class="values-row"><span>01</span><h3>Experiência.</h3><p>Uma história em ótica que começou em 1990.</p></div><div class="values-row"><span>02</span><h3>Proximidade.</h3><p>Tempo para ouvir e entender sua escolha.</p></div><div class="values-row"><span>03</span><h3>Personalidade.</h3><p>Respeito ao seu jeito de ver e de se expressar.</p></div></section>${cta('Sua história também<br><em>tem lugar aqui.</em>')}`);

page('visite','Visite nossa loja em Curitiba','Encontre a Óptica Ocular na Rua Bispo Dom José, 2655, Seminário, Curitiba. Horários, localização e contato pelo WhatsApp.','visite',`
${breadcrumb([['Visite a loja']])}<section class="visit-hero"><div><p class="eyebrow">Estamos aqui, em Curitiba</p><h1>Vamos olhar<br><em>de perto?</em></h1><p class="lead">A próxima escolha pode começar<br>com uma boa conversa.</p>${link('#conversa','Comece pelo WhatsApp','button')}</div><div class="address-card"><span class="eyebrow">O endereço do seu próximo olhar</span><p class="address-number">2655<span aria-hidden="true">.</span></p><address>Rua Bispo Dom José<br>Seminário · Curitiba, PR<br><span>CEP 80440-080</span></address>${link(route,'Trace sua rota')}</div></section>
<section class="visit-details section"><div class="hours-block"><p class="eyebrow">Portas abertas</p><h2>Encontre o<br><em>seu momento.</em></h2><dl><div><dt>Segunda a sexta</dt><dd>9h às 18h30</dd></div><div><dt>Sábado</dt><dd>9h às 13h</dd></div><div><dt>Domingo</dt><dd>Fechado</dd></div></dl><p class="small-note">Em feriados, consulte nossa equipe.</p></div><div class="contact-block"><p class="eyebrow">Fale com a Ocular</p><a class="large-contact" href="${generic}" target="_blank" rel="noopener noreferrer">(41) 99750-2091 ${arrow}</a><span class="small-note">WhatsApp</span><div class="contact-secondary"><a href="tel:+554130169654">Telefone · (41) 3016-9654</a><a href="mailto:optica-ocular@hotmail.com">optica-ocular@hotmail.com</a></div><p>Traga sua receita, seus óculos atuais<br>e as suas ideias. Vamos conversar.</p></div></section>
<section class="map-section" aria-label="Localização da loja"><div class="map-placeholder"><span class="map-pin" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.2"><path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 0 1 14 0Z"/><circle cx="12" cy="10" r="2.5"/></svg></span><p class="eyebrow">Óptica Ocular / Curitiba</p><h2>Esperamos <em>você.</em></h2><p>Rua Bispo Dom José, 2655 · Seminário</p>${link(route,'Abrir localização no Google Maps','button')}<span class="small-note">Escolha seu ponto de partida e trace sua rota.</span></div></section>
<section class="section conversation" id="conversa"><div><p class="eyebrow">Um primeiro contato</p><h2>Conte o que<br><em>você procura.</em></h2><p>Prepare sua mensagem.<br>A conversa continua no WhatsApp.</p>${link('duvidas.html','Prefere esclarecer uma dúvida?')}</div><form id="conversation-form"><label class="field-label" for="contact-name">Como podemos chamar você? <span>(opcional)</span></label><input id="contact-name" name="nome" type="text" autocomplete="given-name" maxlength="60" placeholder="Seu primeiro nome"><fieldset><legend>Quero conversar sobre</legend><div class="interest-options">${['Óculos de grau','Óculos de sol','Lentes','Minha visita'].map((s,i)=>`<label><input type="radio" name="interesse" value="${s}" ${i===0?'checked':''}><span>${s}</span></label>`).join('')}</div></fieldset><label class="field-label" for="contact-note">Algo que gostaria de contar? <span>(opcional)</span></label><textarea id="contact-note" name="mensagem" rows="3" maxlength="500" placeholder="Seu estilo, uma preferência ou uma dúvida."></textarea><div class="message-preview" hidden><span class="eyebrow">Sua mensagem</span><p id="message-preview"></p></div><a class="button" id="conversation-link" href="${generic}" target="_blank" rel="noopener noreferrer">Continuar no WhatsApp ${arrow}</a><p class="small-note">Você revisa e envia a mensagem no WhatsApp. <a href="privacidade.html">Privacidade</a>.</p><noscript><p class="small-note">Inicie a conversa pelo link e conte suas preferências diretamente à equipe.</p></noscript></form></section>`,{og:'gesto-cuidado'});

page('duvidas','Dúvidas frequentes','Respostas sobre armações, lentes, disponibilidade, atendimento e visita à Óptica Ocular em Curitiba.','',`
${breadcrumb([['Dúvidas frequentes']])}<section class="text-hero"><p class="eyebrow">Antes de escolher</p><h1>Mais clareza.<br><em>Desde o começo.</em></h1><p class="lead">Respostas para chegar mais perto<br>da sua próxima escolha.</p></section><section class="section faq-directory"><aside><p class="eyebrow">Encontre sua resposta</p><div class="faq-tools" hidden><label for="faq-search">Busque por um assunto</label><div class="search-field"><input id="faq-search" type="search" placeholder="Ex.: receita, prazo, visita" autocomplete="off"><span aria-hidden="true">⌕</span></div><div class="faq-filters" role="group" aria-label="Filtrar perguntas por assunto">${['Todas','Escolha','Lentes','Compra','Visita'].map((s,i)=>`<button type="button" data-filter="${s}" aria-pressed="${i===0}">${s}<span aria-hidden="true">↗</span></button>`).join('')}</div></div><p class="muted">Sua dúvida é mais específica?</p>${link(generic,'Converse com a equipe')}</aside><div><p class="faq-count small-note" aria-live="polite" hidden></p><div id="faq-results">${faqRows(faqs,true)}</div><div class="faq-empty" hidden><h3>Vamos encontrar<br><em>essa resposta.</em></h3><p>Não encontramos perguntas para essa busca. Tente outra palavra ou converse com a equipe.</p><button type="button" class="text-link" id="clear-search">Limpar busca ${arrow}</button></div></div></section>${cta('Uma boa escolha<br><em>começa sem dúvidas.</em>')}`);

page('privacidade','Privacidade','Saiba como funcionam os contatos, os links externos e o mapa no site da Óptica Ocular.','',`
${breadcrumb([['Privacidade']])}<section class="text-hero"><p class="eyebrow">Transparência</p><h1>Sua conversa.<br><em>Seu controle.</em></h1><p class="lead">Informações sobre o funcionamento deste site.</p></section><article class="privacy-content section"><section><h2>Contato pelo WhatsApp</h2><p>As preferências selecionadas e os textos digitados na página de visita são usados no seu navegador para preparar uma mensagem. O site não mantém um cadastro nem envia esses campos a um servidor da Ocular.</p><p>Ao abrir o WhatsApp, o texto preparado é incluído no link para esse serviço. Você pode revisar a mensagem e decide se deseja enviá-la. O WhatsApp tem suas próprias regras de privacidade.</p></section><section><h2>Mapa e links externos</h2><p>A página de visita oferece um link para abrir a localização no Google Maps. A home contém um mapa integrado. Esses serviços podem processar informações de navegação, como o endereço IP, conforme suas próprias políticas.</p><p>Os links para Google Maps, Instagram, Facebook e WhatsApp levam a serviços de terceiros.</p></section><section><h2>Navegação neste site</h2><p>Esta versão não inclui ferramentas de publicidade ou medição de audiência, nem grava as preferências do formulário em cookies ou no armazenamento local. O serviço usado para hospedar o site pode manter registros técnicos de acesso.</p></section><section><h2>Fale com a Ocular</h2><p>Para dúvidas sobre os dados compartilhados durante o atendimento, entre em contato pelo e-mail <a href="mailto:optica-ocular@hotmail.com">optica-ocular@hotmail.com</a> ou pelo telefone <a href="tel:+554130169654">(41) 3016-9654</a>.</p></section><p class="small-note">Atualizado em 25 de setembro de 2026.</p></article>`);

page('404','Página não encontrada','Encontre óculos, lentes e informações de contato da Óptica Ocular.','',`<section class="text-hero error-page"><p class="eyebrow">404 / Um novo caminho</p><h1>Vamos mudar<br><em>o ponto de vista?</em></h1><p class="lead">Não encontramos esta página.<br>Escolha por onde continuar.</p><div class="error-links">${link('index.html','Voltar ao início','button')}${link('oculos.html','Explorar óculos')}</div></section>`);
fs.writeFileSync(path.join(root,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${base}/</loc></url>${pages.map(p=>`<url><loc>${base}/${p}</loc></url>`).join('')}</urlset>\n`);
fs.writeFileSync(path.join(root,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${base}/sitemap.xml\n`);
console.log(`Geradas ${pages.length} páginas internas, página 404 e sitemap. Home preservada.`);
